apiVersion: v1
kind: Namespace
metadata:
  name: arthasx
  labels:
    app.kubernetes.io/name: arthasx
    app.kubernetes.io/part-of: arthasx

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: arthasx-serviceaccount
  namespace: arthasx
  labels:
    app.kubernetes.io/name: arthasx
    app.kubernetes.io/part-of: arthasx

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: arthasx-clusterrole
  labels:
    app.kubernetes.io/name: arthasx
    app.kubernetes.io/part-of: arthasx
rules:
  - apiGroups: [""]
    resources: ["pods","services","pods/exec"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: arthasx-role
  namespace: arthasx
  labels:
    app.kubernetes.io/name: arthasx
    app.kubernetes.io/part-of: arthasx
rules:
  - apiGroups:
      - ""
    resources: ["pods","services"]   
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: arthasx-role-binding
  namespace: arthasx
  labels:
    app.kubernetes.io/name: arthasx
    app.kubernetes.io/part-of: arthasx
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: arthasx-role
subjects:
  - kind: ServiceAccount
    name: arthasx-serviceaccount
    namespace: arthasx

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: arthasx-clusterrole-binding
  labels:
    app.kubernetes.io/name: arthasx
    app.kubernetes.io/part-of: arthasx
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: arthasx-clusterrole
subjects:
  - kind: ServiceAccount
    name: arthasx-serviceaccount
    namespace: arthasx

---
apiVersion: v1
kind: Service
metadata:
  name: arthasx-controller-service
  namespace: arthasx
spec:
  selector:
    app: arthasx-controller
  ports: 
  - name: app
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30080
  - name: tunnel-web
    protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 30081
  - name: tunnel-server
    port: 7777
    protocol: TCP
    targetPort: 7777
    nodePort: 30077
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: arthasx-controller
  namespace: arthasx
spec: 
  selector:
    matchLabels:
      app: arthasx-controller
  replicas: 1
  template: 
    metadata:
      labels:
        app: arthasx-controller
    spec: 
      serviceAccountName: arthasx-serviceaccount
      containers: 
      - name: arthasx-controller
        image: arthasx-controller
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        - containerPort: 8081 
        - containerPort: 7777
        env:
        - name: JAVA_OPTS
          value: -Darthasx.attach.redirect.tunnelWebPort=30081 -Darthasx.attach.redirect.tunnelServerPort=30077 
        - name: TUNNEL_SERVER_JAVA_OPTS
          value:  
