apiVersion: apps/v1
kind: Deployment
metadata: 
  name: arthasx-sample-k8s
spec: 
  selector:
    matchLabels:
      app: arthasx-sample-k8s
  replicas: 2
  template: 
    metadata:
      labels:
        app: arthasx-sample-k8s
        arthasx: v1 #required ,for search
      annotations:
        arthasx.jps.keywords: "arthasx-sample-k8s.jar" #search for JVM PID ,defualt app.jar
    spec:
      initContainers:
      - name: arthasx-init
        image: arthasx-init
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: arthasxhome #fixed name use for attach
          mountPath: /var/lib/arthasx #fixed value
      containers: 
      - name: arthasx-sample-k8s
        image: arthasx-sample-k8s
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: arthasxhome
          mountPath: /opt/arthasx
      volumes:
      - name: arthasxhome
        emptyDir: {}
